const DELIVER_JOKES_QUEUE = 'deliver_jokes'
const DELIVER_JOKES_SERVICE = 'DELIVER_JOKES'

const SUBMIT_JOKES_QUEUE = 'submit_jokes'
const SUBMIT_JOKES_SERVICE = 'SUBMIT_JOKES'

export {
    DELIVER_JOKES_QUEUE,
    DELIVER_JOKES_SERVICE,
    SUBMIT_JOKES_QUEUE,
    SUBMIT_JOKES_SERVICE
}